### ISSUE TITLE
[idea] Add app comercial as Aliexpress with bi9tcoin payment

### ISSUE THREAD

**Issue by Gabis28Andre** [erskingardner/nostr-how#187]
I'm a programmer I would like to integrate with ours in creating commercial applications, how do I do it, how do I publish, should they do tutorials on uploading apps... iam brazilian :-)

**Comment by erskingardner** [comment]
Same here. This isn't the best venue for these sorts of requests. I made a [few videos](https://www.youtube.com/channel/UCwjWOu_QJCjusHKlOo9_52w) on Youtube a while ago about using [NDK](https://github.com/nostr-dev-kit/ndk) that you might find helpful though (they are a little out of date)
