### ISSUE TITLE
[idea]  Create your own browser or system that only uses the nostr protocol

### ISSUE THREAD

**Issue by Gabis28Andre** [erskingardner/nostr-how#188]
Create your own browser or system that only uses nostr protocol apps, or create a linux system that only has apps based on nostr. 
I would like to contribute and work on the project in this sense, but I need help, collaborators, and attention from the creators

**Comment by erskingardner** [comment]
Hey @Gabis28Andre - this repo is for an informational site, it's not a place to look for collaborators on other projects. I'm going to close this. I'd definitely start asking around on Nostr though.
