### ISSUE TITLE
Add option 0 for NIP-05 verification (Free providers)

### ISSUE THREAD

**Issue by quentintaranpino** [erskingardner/nostr-how#60]
There are a lot of free providers for NIP-05 verification. I think this option should also be exposed.

Change this page:
https://nostr.how/verify-your-identity

With:

**Option 0: Select a free provider for verification**

There are numerous free NIP-05 verification providers, such as https://nostrcheck.me https://nostr.industries 

By filling out a form you get your verification instantly.

**(Clarification, I am the developer of nostrcheck.me)**

**Comment by erskingardner** [comment]
Coming soon in an update. ;)

**Comment by erskingardner** [comment]
Closed with the updates from today.
