### ISSUE TITLE
Guides section | Spanish Translation

### ISSUE THREAD

**Issue by maemultichain** [erskingardner/nostr-how#83]
As a user of the website and spanish speaker, I'd like to have the **Guide contents** in this language to expand the education about Nostr to other non-english speakers of Latin-America or Spain.

**Comment by alvarohghg** [comment]
Good evening,
I'm interested in this issue, could I have it assigned to me?

**Comment by erskingardner** [comment]
@alvarohghg – sorry I missed this comment until now (need to sort out my GH notifications. I think that @maemultichain might have started on translating the guides here but the more the merrier! Unless all the pages are done, I'm sure we'd welcome your help.

**Comment by erskingardner** [comment]
Spanish is launched!
